services:
  postgres:
    image: postgres:16-alpine
    container_name: echosense-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: echosense_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./backend/Echosense/Echosense
    container_name: echosense-app
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/echosense_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgrespassword
    depends_on:
      - postgres

volumes:
  postgres_data: